# Generated by Django 3.0.6 on 2025-12-26 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('lideranca', models.CharField(default='Não informado', max_length=200, null=True)),
                ('fone', models.CharField(default='Não informado', max_length=50, null=True)),
                ('endereco', models.TextField()),
                ('numero', models.CharField(default='Não informado', max_length=20, null=True)),
                ('email', models.CharField(default='Não informado', max_length=100, null=True)),
                ('bairro', models.CharField(default='Não informado', max_length=100, null=True)),
                ('cidade', models.CharField(default='Não informado', max_length=100, null=True)),
                ('uf', models.CharField(default='Não informado', max_length=20, null=True)),
                ('zona', models.CharField(default='Não informado', max_length=20, null=True)),
                ('secao', models.CharField(default='Não informado', max_length=20, null=True)),
                ('ativo', models.IntegerField(default=1)),
                ('dia_aniv', models.IntegerField(default=0)),
                ('mes_aniv', models.IntegerField(default=0)),
                ('ano_aniv', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Hist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_id_original', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('lideranca', models.CharField(default='Não informado', max_length=200)),
                ('fone', models.CharField(max_length=50)),
                ('endereco', models.TextField()),
                ('numero', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=20)),
                ('zona', models.CharField(max_length=20)),
                ('secao', models.CharField(max_length=20)),
                ('ativo', models.IntegerField(default=1)),
                ('dia_aniv', models.IntegerField()),
                ('mes_aniv', models.IntegerField()),
                ('ano_aniv', models.IntegerField()),
                ('operacao', models.CharField(choices=[('ALTERACAO', 'Alteração'), ('EXCLUSAO', 'Exclusão')], max_length=10)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
