# Generated by Django 3.0.6 on 2025-12-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente_hist',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente_hist',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
    ]
