# Generated by Django 3.0.6 on 2026-01-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0005_auto_20251229_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='99999999999', max_length=11, null=True),
        ),
    ]
